name: build

on:
    push:
        branches:
            - "main"
    pull_requests:
        branches:
            - "main"
            
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: start
                run: echo "start test"
            
